language: go
sudo: false

go:
  - 1.5
  - tip

env:
  - GO15VENDOREXPERIMENT=1

before_install:
  - sudo apt-get install libpcap-dev

script:
  - go build
  - go vet -v $(go list ./...|grep -v vendor)
  - go test -v $(go list ./...|grep -v vendor)
  