language: go
sudo: false

go:
  - 1.5
  - tip

env:
  - GO15VENDOREXPERIMENT=1

addons:
  apt:
    packages:
      - libpcap-dev

script:
  - go build
  - go vet -v $(go list ./...|grep -v vendor)
  - go test -v $(go list ./...|grep -v vendor)
  